replicaCount: 2

image:
  repository: smithveunsa/react-bun-k8s
  pullPolicy: IfNotPresent
  tag: "backend"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: agentic-api.your-domain.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Environment variables
env:
  POSTGRES_SERVER: "postgres-service"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "changeme-secure-password"
  POSTGRES_DB: "agentic_app"
  POSTGRES_PORT: "5432"
  
  REDIS_URL: "redis://redis-service:6379"
  
  NIM_BASE_URL: "https://integrate.api.nvidia.com/v1"
  NIM_API_KEY: "changeme-nvidia-api-key"
  NIM_MODEL_NAME: "nvidia/llama-3_1-nemotron-nano-8b-v1"
  NIM_EMBEDDING_MODEL: "nvidia/nv-embedqa-e5-v5"
  
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"

# NVIDIA NIM Service Configuration
nimService:
  enabled: true
  replicaCount: 1
  image:
    repository: nvcr.io/nim/meta/llama-3.1-8b-instruct
    tag: "latest"
  resources:
    limits:
      nvidia.com/gpu: 1
      cpu: 4000m
      memory: 8Gi
    requests:
      nvidia.com/gpu: 1
      cpu: 2000m
      memory: 4Gi

# Database Configuration
postgres:
  enabled: true
  image:
    repository: postgres
    tag: "15-alpine"
  persistence:
    enabled: true
    size: 20Gi
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

# Redis Configuration
redis:
  enabled: true
  image:
    repository: redis
    tag: "7-alpine"
  persistence:
    enabled: true
    size: 5Gi
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
